apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server-deployment
  labels:
    app: mysql-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-server
      tier: db
  template:
    metadata:
      labels:
        app: mysql-server
        tier: db
    spec:
      containers:
        - name: mysql-server
          image: mysql:5.7.30
          args:
            - "--ignore-db-dir=lost+found"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-user-pass
                  key: password
          volumeMounts:
            - name: mysql-pv-storage
              mountPath: /var/lib/mysql

      volumes:
        - name: mysql-pv-storage
          persistentVolumeClaim:
            claimName: mysql-server-pv-clain