apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-server-pv-clain
  labels:
    app: mysql-server-pv-clain
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi