apiVersion: v1
kind: Service
metadata:
  name: mysql-server-service
  labels:
    app: mysql-server-service
spec:
  selector:
    app: mysql-server
    tier: db
  ports:
    - protocol: TCP
      port: 3306
  clusterIP: None