apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |

    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Code.education</title>
    </head>
    <body>
      <h2>Code.education Rocks.</h2>
    </body>
    </html>